---
Name: bing-custom-search
---
#Kraftausdruck\Extensions\BingSearchExtender:
#  AccessKey: ''
#  CustomConfig: ''
#  mkt: 'en_US'
PageController:
  extensions:
    - Kraftausdruck\Extensions\BingSearchExtender
